# Generated by Django 2.0 on 2017-12-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difference',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('occurence', models.IntegerField(default=0)),
            ],
        ),
    ]
